language: objective-c
xcode_project: Child.xcodeproj # path to your xcodeproj folder
xcode_scheme: Child
osx_image: xcode9.2
xcode_sdk: macosx10.13

script:
 - swift package update
 - swift package generate-xcodeproj
 - xcodebuild clean test -project Child.xcodeproj -scheme Child CODE_SIGNING_REQUIRED=NO